---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  enabled: true
  options:
    config-file: molecule/default/yaml-lint.yml

platforms:
  - name: ${MOLECULE_DISTRO_NAME:-debian9}
    image: ${MOLECULE_DISTRO:-ultransible/debian_9_systemd:v1}
    pre_build_image: true
    volume_mounts:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    security_opts:
      - seccomp=unconfined
    tmpfs:
      - /run
      - /run/lock
    capabilities:
      - SYS_ADMIN
    privileged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
